version: '2.0'
services:
  jd_cookie:
    image: abcdjd/jd_cookie
    container_name: jd_cookie
    restart: always
    ports:
      - 6789:6789
    environment:
      #控制面板的服务器ip+端口，多个服务器 使用&符号隔开。
      #例如：http://127.0.0.1:8080&http://127.0.0.2:8080
      - UPDATE_API=http://127.0.0.1:8080
      #下面为通知，通知方式见sendNotify.js
      #- QYWX_KEY=
      #- QYWX_AM=
      #- TG_BOT_TOKEN=
      #- TG_USER_ID=
      #- BARK_PUSH=
